### ISSUE TITLE
3.3.5: TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by jcollum-nike** [adriantoine/enzyme-to-json#141]
I'm seeing this in 3.3.5

```
const toShallowJson = wrapper => toJson(wrapper, { mode: 'shallow' });
```

```
...

TypeError: Cannot convert a Symbol value to a string

...

       74 |       expect(wrapper.find('.foo').length).toBe(1);
    > 75 |       expect(toShallowJson(wrapper)).toMatchSnapshot();

...

  at printElement (node_modules/pretty-format/build/plugins/lib/markup.js:108:9)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:25:32)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at prettyFormat (node_modules/pretty-format/build/index.js:526:16)
      at Object.throwingMatcher (node_modules/expect/build/index.js:342:33)
```

Thought shallow mode might help the problem but it happens with 

```
import toJson from 'enzyme-to-json';
...
expect(toJson(wrapper)).toMatchSnapshot();

``` 

as well. 

Maybe I can work around this by detecting the Symbol in `.map`? 

Here's the .debug output of the wrapper: 

```
<div className=\"line-item-group\">
      <div className=\"line-item-group-status mt8-md mt10-sm pb3-md prl5-sm prl0-md flx-dir-md-r flx-dir-sm-c d-md-flx flx-as-sm-c\">
        <div className=\"flx-gro-md-1\">
          <GroupStatus expectedArrivalDate=\"\" isRecentlyCancelled={false} onlineOrder={true} returnCreatedDate={{...}} status=\"returnCompleted\" />
        </div>
        <div className=\"line-item-group-cta mt0-md mb0-md mt7-sm mb9-sm d-sm-flx flx-dir-sm-c flx-dir-md-r\">
          <CancelButton onClick={[Function: mockConstructor]} trackButtonProps={{...}} trackCancelOrder={[Function: mockConstructor]} className=\"ncss-btn-primary-dark d-sm-ib d-md-b order-detail-cancel-order-button\" text=\"Cancel\" />
        </div>
      </div>
      <div className=\"order-detail-line-items prl5-sm prl0-md flx-dir-sm-c flx-wr-sm-nw flx-wr-md-w d-sm-flx\">
        <Symbol(react.fragment)>
          <Symbol(react.fragment)>
            <OrderLineItemCard colorDescription=\"\" currency=\"\" description=\"\" productInfo={{...}} listPrice={2} quantity={0} retailPrice={1.5} size=\"\" skuId={[undefined]} trackClick={[Function: mockConstructor]} unitPrice={0} />
          </Symbol(react.fragment)>
        </Symbol(react.fragment)>
      </div>
    </div>
```

**Comment by jcollum** [comment]
Closing, went away when I updated to current version of Enzyme.

**Comment by jcollum-nike** [comment]
Closing, went away when I updated to current version of Enzyme.
