### ISSUE TITLE
TypeError when serializing Fragment

### ISSUE THREAD

**Issue by alexlrobertson** [adriantoine/enzyme-to-json#89]
[React@16.2 Fragments](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#what-are-fragments) fail to serialize.

TypeError: Cannot convert a Symbol value to a string

```jsx
import React, { Fragment } from 'react';
import { shallow } from 'enzyme';

function AnotherComponent() {
    return (
        <Fragment>
            <li>First</li>
            <li>Second</li>
        </Fragment>
    );
}

function Component() {
    return (
        <ul>
            <AnotherComponent />
        </ul>
    );
}

test('renders', () => {
    const wrapper = shallow(<Component />)
        .find('AnotherComponent')
        .dive();

    expect(wrapper).toMatchSnapshot();
});
```

**Comment by adriantoine** [comment]
Hi!
Thanks for reporting the issue, that's a good one, I'll look at supporting React fragments as soon as I can.

**Comment by rholliger** [comment]
Any updates on this matter?

**Comment by adriantoine** [comment]
I didn't have time to work on this recently but I would gladly accept a PR.

**Comment by madou** [comment]
here you go: https://github.com/adriantoine/enzyme-to-json/pull/90

**Comment by adriantoine** [comment]
Thanks to @madou, `enzyme-to-json` now supports React Fragments 🎉

**Comment by th3fallen** [comment]
wanna tag a version please sir?

**Comment by adriantoine** [comment]
@th3fallen a new version has been published already, it's [`3.3.0`](https://github.com/adriantoine/enzyme-to-json/releases/tag/v3.3.0).

**Comment by th3fallen** [comment]
sorry, i was blind, thanks!

**Comment by chandlera** [comment]
@adriantoine would there be a similar fix for React.Suspense?

**Comment by adriantoine** [comment]
@chandlera Hey! Sorry for the lack of support recently. I will have a look asap but I'll accept a PR as well.

**Comment by jcollum-nike** [comment]
I'm seeing this in 3.3.5

```
TypeError: Cannot convert a Symbol value to a string

...

        74 |       expect(wrapper.find('.foo').length).toBe(1);
    > 75 |       expect(toShallowJson(wrapper)).toMatchSnapshot();

...

  at printElement (node_modules/pretty-format/build/plugins/lib/markup.js:108:9)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:25:32)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at children.map.child (node_modules/pretty-format/build/plugins/lib/markup.js:67:13)
          at Array.map (<anonymous>)
      at printChildren (node_modules/pretty-format/build/plugins/lib/markup.js:61:6)
      at Object.serialize (node_modules/pretty-format/build/plugins/ReactTestComponent.js:39:39)
      at printPlugin (node_modules/pretty-format/build/index.js:309:16)
      at prettyFormat (node_modules/pretty-format/build/index.js:526:16)
      at Object.throwingMatcher (node_modules/expect/build/index.js:342:33)
```
